/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "c2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(c2_Command, c2_Command, 2)


PB_BIND(c2_AgentMessage, c2_AgentMessage, 2)





